name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        id: setup-node
        continue-on-error: true
        with:
          node-version: 20
          cache: "pnpm"
      - run: |
          corepack disable
          npm install -g pnpm@latest
        if: ${{ success() && steps.setup-node.outcome == 'failure' }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
        if: ${{ success() && steps.setup-node.outcome == 'failure' }}
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
        with:
          commit-message: "chore: apply automated lint fixes"
